package Database;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author db2inst226
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        tFName = new javax.swing.JTextField();
        tFGender = new javax.swing.JTextField();
        tFCountry = new javax.swing.JTextField();
        tFPhone = new javax.swing.JTextField();
        checkInLabel = new javax.swing.JLabel();
        txtdateCheckOut = new com.toedter.calendar.JDateChooser();
        checkOutLabel = new javax.swing.JLabel();
        txtdateCheckin = new com.toedter.calendar.JDateChooser();
        roomLabel = new javax.swing.JLabel();
        tFRoomNumber = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textPrimary = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        nameLabel.setText("Name");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(40, 140, 40, 20);

        genderLabel.setText("Gender");
        jPanel1.add(genderLabel);
        genderLabel.setBounds(40, 210, 50, 20);

        countryLabel.setText("Country");
        jPanel1.add(countryLabel);
        countryLabel.setBounds(40, 270, 50, 20);

        phoneLabel.setText("Phone");
        jPanel1.add(phoneLabel);
        phoneLabel.setBounds(40, 340, 50, 20);

        tFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNameActionPerformed(evt);
            }
        });
        jPanel1.add(tFName);
        tFName.setBounds(110, 140, 120, 30);

        tFGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFGenderActionPerformed(evt);
            }
        });
        jPanel1.add(tFGender);
        tFGender.setBounds(110, 210, 120, 30);

        tFCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFCountryActionPerformed(evt);
            }
        });
        jPanel1.add(tFCountry);
        tFCountry.setBounds(110, 270, 120, 30);

        tFPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(tFPhone);
        tFPhone.setBounds(110, 340, 120, 30);

        checkInLabel.setText("Check In");
        jPanel1.add(checkInLabel);
        checkInLabel.setBounds(270, 220, 60, 20);

        txtdateCheckOut.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtdateCheckOut);
        txtdateCheckOut.setBounds(350, 270, 120, 30);

        checkOutLabel.setText("Check Out");
        jPanel1.add(checkOutLabel);
        checkOutLabel.setBounds(270, 280, 60, 20);

        txtdateCheckin.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txtdateCheckin);
        txtdateCheckin.setBounds(350, 210, 120, 30);

        roomLabel.setText("Room Number");
        jPanel1.add(roomLabel);
        roomLabel.setBounds(260, 140, 100, 30);
        jPanel1.add(tFRoomNumber);
        tFRoomNumber.setBounds(350, 140, 120, 30);

        numberLabel.setText("Customer ID");
        jPanel1.add(numberLabel);
        numberLabel.setBounds(30, 40, 110, 30);

        jButton1.setText("Confirm Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 430, 100, 40);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 430, 90, 40);

        textPrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrimaryActionPerformed(evt);
            }
        });
        jPanel1.add(textPrimary);
        textPrimary.setBounds(110, 40, 120, 30);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Background\\AddBackground.png")); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNameActionPerformed

    private void tFGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFGenderActionPerformed

    private void tFCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFCountryActionPerformed

    private void tFPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFPhoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Query newCustomer = new Query();

        //deklarasi
        String name;
        String gender;
        String country;
        String phone;
        String checkIn;
        String checkOut;
        int roomNumber;
        int number;
        int total = 0;
        
        try {
            //pengisian variabel
            number = Integer.parseInt(textPrimary.getText());
            name = tFName.getText();
            gender = tFGender.getText();
            country = tFCountry.getText();
            phone = tFPhone.getText();
            checkIn = ((JTextField) txtdateCheckin.getDateEditor().getUiComponent()).getText();
            checkOut = ((JTextField) txtdateCheckOut.getDateEditor().getUiComponent()).getText();
            roomNumber = Integer.parseInt(tFRoomNumber.getText());

            //hitung Total
            total = hitungTotal(checkIn, checkOut, roomNumber);

            //masuk ke query
            newCustomer.addCostumer(number, name, gender, country, phone, checkIn, checkOut, roomNumber);
            newCustomer.addPayment(number, roomNumber, total);
            this.setVisible(false);
            
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Silahkan Masukkan Data dengan Benar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public int hitungTotal(String dateStart, String dateStop, int room_number) {
        int lama;
        Date checkIn, checkOut;
        int cost_per_night;
        int total = 0;

        //HH converts hour in 24 hours format (0-23), day calculation
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        
        Date d1 = null;
        Date d2 = null;
        try {
            d1 = format.parse(dateStart);
            d2 = format.parse(dateStop);

            //in milliseconds
            long diff = d2.getTime() - d1.getTime();
            long diffDays = diff / (24 * 60 * 60 * 1000);

            if (room_number == 1) {
                cost_per_night = 100000;
            } else if (room_number == 2) {
                cost_per_night = 200000;
            } else if (room_number == 3) {
                cost_per_night = 200000;
            } else {
                cost_per_night = 300000;
            }
            
            total = (int) (diffDays * cost_per_night);
            
            System.out.print(diffDays + " days, ");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Silahkan Masukkan Tanggal Check In/Check Out dengan Benar");
        }
        return total;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.setVisible(false);
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void textPrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrimaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrimaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JTextField tFCountry;
    private javax.swing.JTextField tFGender;
    private javax.swing.JTextField tFName;
    private javax.swing.JTextField tFPhone;
    private javax.swing.JTextField tFRoomNumber;
    private javax.swing.JTextField textPrimary;
    private com.toedter.calendar.JDateChooser txtdateCheckOut;
    private com.toedter.calendar.JDateChooser txtdateCheckin;
    // End of variables declaration//GEN-END:variables
}
