package Database;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author db2inst226
 */
public class DeleteCustomer extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCustomer
     */
    String key;

    public DeleteCustomer() throws SQLException {
        initComponents();
        this.setTitle("Delete Customer");
    }

    public DefaultTableModel updateTable() throws SQLException {
        Query tampil = new Query();
        ResultSet rs = tampil.customerInfo();

        DefaultTableModel dtm = new DefaultTableModel();
        int colum;

        ResultSetMetaData rsmeta = rs.getMetaData();
        colum = rsmeta.getColumnCount() + 1;

        Vector colum_name = new Vector();
        Vector data_rows = new Vector();

        for (int i = 1; i < colum; i++) {
            colum_name.addElement(rsmeta.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colum_name);

        while (rs.next()) {

            data_rows = new Vector();
            for (int j = 1; j < colum; j++) {
                data_rows.addElement(rs.getString(j));
            }
            dtm.addRow(data_rows);
        };
        return dtm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteLabel = new javax.swing.JLabel();
        nameLabelUpdate = new javax.swing.JLabel();
        genderLabelUpdate = new javax.swing.JLabel();
        countryLabelUpdate = new javax.swing.JLabel();
        roomNumLabelUpdate = new javax.swing.JLabel();
        checkInUpdate = new javax.swing.JLabel();
        checkOutUpdate = new javax.swing.JLabel();
        phoneUpdate = new javax.swing.JLabel();
        tFkey = new javax.swing.JTextField();
        confirmDelete = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        checkInLabel = new javax.swing.JLabel();
        checkOutLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        deleteLabel.setText(" Customer ID");
        jPanel1.add(deleteLabel);
        deleteLabel.setBounds(30, 30, 110, 40);
        jPanel1.add(nameLabelUpdate);
        nameLabelUpdate.setBounds(120, 150, 120, 30);
        jPanel1.add(genderLabelUpdate);
        genderLabelUpdate.setBounds(120, 220, 120, 30);
        jPanel1.add(countryLabelUpdate);
        countryLabelUpdate.setBounds(120, 280, 120, 30);
        jPanel1.add(roomNumLabelUpdate);
        roomNumLabelUpdate.setBounds(350, 150, 120, 30);
        jPanel1.add(checkInUpdate);
        checkInUpdate.setBounds(350, 220, 130, 30);
        jPanel1.add(checkOutUpdate);
        checkOutUpdate.setBounds(350, 280, 120, 30);
        jPanel1.add(phoneUpdate);
        phoneUpdate.setBounds(120, 350, 120, 30);

        tFkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFkeyActionPerformed(evt);
            }
        });
        jPanel1.add(tFkey);
        tFkey.setBounds(120, 40, 120, 30);

        confirmDelete.setText("Confirm Delete");
        confirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(confirmDelete);
        confirmDelete.setBounds(360, 430, 120, 40);

        ok.setText("Search");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(260, 40, 90, 30);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 430, 90, 40);

        nameLabel.setText("Name");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(30, 160, 40, 20);

        genderLabel.setText("Gender");
        jPanel1.add(genderLabel);
        genderLabel.setBounds(30, 230, 50, 20);

        countryLabel.setText("Country");
        jPanel1.add(countryLabel);
        countryLabel.setBounds(30, 290, 50, 20);

        phoneLabel.setText("Phone");
        jPanel1.add(phoneLabel);
        phoneLabel.setBounds(30, 360, 50, 20);

        roomLabel.setText("Room Number");
        jPanel1.add(roomLabel);
        roomLabel.setBounds(260, 150, 90, 30);

        checkInLabel.setText("Check In");
        jPanel1.add(checkInLabel);
        checkInLabel.setBounds(260, 230, 60, 20);

        checkOutLabel.setText("Check Out");
        jPanel1.add(checkOutLabel);
        checkOutLabel.setBounds(260, 290, 60, 20);

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Background\\DeleteBackground.png")); // NOI18N
        background.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                backgroundFocusGained(evt);
            }
        });
        jPanel1.add(background);
        background.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_backgroundFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundFocusGained

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        try {
            updateTable();
            this.key = tFkey.getText();
            int noFindRow = 0;

            for (int i = 0; i < updateTable().getRowCount(); i++) {
                if (key.equals(updateTable().getValueAt(i, 0))) {
                    noFindRow = i;
                    break;
                } else {
                    noFindRow = -1;
                }
            }

            for (int j = 0; j < updateTable().getColumnCount(); j++) {
                System.out.println("" + updateTable().getValueAt(noFindRow, j));
            }
            nameLabelUpdate.setText((String) updateTable().getValueAt(noFindRow, 1));
            genderLabelUpdate.setText((String) updateTable().getValueAt(noFindRow, 2));
            countryLabelUpdate.setText((String) updateTable().getValueAt(noFindRow, 3));
            phoneUpdate.setText((String) updateTable().getValueAt(noFindRow, 4));
            checkInUpdate.setText((String) updateTable().getValueAt(noFindRow, 5));
            checkOutUpdate.setText((String) updateTable().getValueAt(noFindRow, 6));
            roomNumLabelUpdate.setText((String) updateTable().getValueAt(noFindRow, 7));

        } catch (Exception e) {
            nameLabelUpdate.setText("");
            genderLabelUpdate.setText("");
            countryLabelUpdate.setText("");
            phoneUpdate.setText("");
            checkInUpdate.setText("");
            checkOutUpdate.setText("");
            roomNumLabelUpdate.setText("");
            JOptionPane.showMessageDialog(this, "Customer Tidak Ditemukan !");
        }
    }//GEN-LAST:event_okActionPerformed

    private void tFkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFkeyActionPerformed

    private void confirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDeleteActionPerformed
        Query newCustomer = new Query();
        try {
            for (int i = 0; i < updateTable().getRowCount(); i++) {
                if (key.equals(updateTable().getValueAt(i, 0))) {

                    newCustomer.deleteCustomerPayment(Integer.parseInt(key));
                    newCustomer.deleteCustomer(Integer.parseInt(key));
                    JOptionPane.showMessageDialog(this, "Berhasil Menghapus Customer dengan Customer ID : " + key);
                    nameLabelUpdate.setText("");
                    genderLabelUpdate.setText("");
                    countryLabelUpdate.setText("");
                    phoneUpdate.setText("");
                    checkInUpdate.setText("");
                    checkOutUpdate.setText("");
                    roomNumLabelUpdate.setText("");
                    this.setVisible(false);
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Customer Tidak Ditemukan !");
                    break;
                }
            }

        } catch (Exception e) {
            nameLabelUpdate.setText("");
            genderLabelUpdate.setText("");
            countryLabelUpdate.setText("");
            phoneUpdate.setText("");
            checkInUpdate.setText("");
            checkOutUpdate.setText("");
            roomNumLabelUpdate.setText("");
            JOptionPane.showMessageDialog(this, "Customer Tidak Ditemukan !");
        }
       
    }//GEN-LAST:event_confirmDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteCustomer().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel checkInLabel;
    private javax.swing.JLabel checkInUpdate;
    private javax.swing.JLabel checkOutLabel;
    private javax.swing.JLabel checkOutUpdate;
    private javax.swing.JButton confirmDelete;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel countryLabelUpdate;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabelUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabelUpdate;
    private javax.swing.JButton ok;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneUpdate;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JLabel roomNumLabelUpdate;
    private javax.swing.JTextField tFkey;
    // End of variables declaration//GEN-END:variables
}
