package Database;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


/**
 *
 * @author db2inst226
 */
public class Main_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    JFrame login;

    public Main_Menu(JFrame login) {

        this.login = login;
        this.setTitle("Main Menu");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        addCustomerLabel = new javax.swing.JLabel();
        editCustomerLAbel = new javax.swing.JLabel();
        deleteCustomerLabel = new javax.swing.JLabel();
        infoCustomerLabel = new javax.swing.JLabel();
        paymentInfoLabel = new javax.swing.JLabel();
        roomInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomInfoIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Background\\logo.png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 10, 300, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Logout.png")); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 360, 80, 80);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Payment Info.png")); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 100, 70, 80);

        logoutLabel.setText("Logout");
        jPanel1.add(logoutLabel);
        logoutLabel.setBounds(410, 440, 50, 20);

        addCustomerLabel.setText("Add Customer");
        jPanel1.add(addCustomerLabel);
        addCustomerLabel.setBounds(40, 180, 110, 14);

        editCustomerLAbel.setText("Edit Customer");
        jPanel1.add(editCustomerLAbel);
        editCustomerLAbel.setBounds(40, 300, 120, 14);

        deleteCustomerLabel.setText("Delete Customer");
        jPanel1.add(deleteCustomerLabel);
        deleteCustomerLabel.setBounds(40, 430, 100, 14);

        infoCustomerLabel.setText("Customer Info");
        jPanel1.add(infoCustomerLabel);
        infoCustomerLabel.setBounds(190, 300, 90, 14);

        paymentInfoLabel.setText("Payment Info");
        jPanel1.add(paymentInfoLabel);
        paymentInfoLabel.setBounds(190, 180, 90, 14);

        roomInfo.setText("Room Info");
        jPanel1.add(roomInfo);
        roomInfo.setBounds(200, 430, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Add.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 80, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Edit.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 210, 80, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Personal information.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 210, 70, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Remove.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 340, 80, 110);

        roomInfoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Icon\\Room Info.png")); // NOI18N
        roomInfoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roomInfoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomInfoIconMouseClicked(evt);
            }
        });
        jPanel1.add(roomInfoIcon);
        roomInfoIcon.setBounds(190, 360, 70, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\db2inst226\\Documents\\NetBeansProjects\\DB2HotelManagement\\src\\Database\\Background\\MainMenuBackground.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(516, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Add addWin = new Add();
        addWin.setSize(500, 530);
        addWin.setVisible(true);
        addWin.setTitle("Add Customer");

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            Customer_Payment_Info gui = new Customer_Payment_Info();
            gui.setVisible(true);
            gui.setTitle("Customer Payment Information");
        } catch (SQLException ex) {
            Logger.getLogger(Customer_Payment_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            CustomerInfo gui = new CustomerInfo();
            gui.setVisible(true);
            gui.setTitle("Customer Personal Information");
        } catch (SQLException ex) {
            Logger.getLogger(Customer_Payment_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            new DeleteCustomer().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(DeleteCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new updateCustomer().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void roomInfoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomInfoIconMouseClicked
        try {
            new RoomInfo().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RoomInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_roomInfoIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //  java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main_Menu().setVisible(true);
//            }
        //  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCustomerLabel;
    private javax.swing.JLabel deleteCustomerLabel;
    private javax.swing.JLabel editCustomerLAbel;
    private javax.swing.JLabel infoCustomerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel paymentInfoLabel;
    private javax.swing.JLabel roomInfo;
    private javax.swing.JLabel roomInfoIcon;
    // End of variables declaration//GEN-END:variables
}
